# name: Publish Docker Image

# on:
#   push:
#     branches: [ "main" ]
  
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#     - uses: actions/checkout@v4

#     - name: Login to docker hub
#      run: echo "${{secrets.DOCKER_SECRET}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
     
name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{secrets.DOCKER_SECRET}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/docker-aws-cicd:latest
      